### ISSUE TITLE
Adding new instruments - any documentation?

### ISSUE THREAD

**Issue by svgeesus** [PhilippCo/testgear#1]
I see documentation on how to use testgear lib, but not on adding new instruments.

For my own use, I miss temperature and humidity sensors, and also I would like to add support for the [PDVS2mini programmable voltage source](https://www.ianjohnston.com/index.php/onlineshop/handheld-precision-digital-voltage-source-2-mini-detail) from Ian Johnston. It uses a serial interface.

I guess these are all low-level interfaces, not using GPIB or anything like that. 

(I looked for a thread about testgear lib on EEVblog forum but didn't find one, so I am raising the issue here).

**Comment by PhilippCo** [comment]
Hi Chris,

I think it is always a good idea to add more instruments.

There is just a folder for every manufacturer and then a file for each
instrument.

It would be nice if the voltage source would get the same interface as all
the other sources. This way it would be easy to use this source or another
with the same measurement script.

Best regards
Philipp

Am Mo., 2. Mai 2022 um 00:48 Uhr schrieb Chris Lilley <
***@***.***>:

**Comment by svgeesus** [comment]
> It would be nice if the voltage source would get the same interface as all
the other sources. This way it would be easy to use this source or another
with the same measurement script.

Yes, absolutely. That is a thing I really like about this library.

Don't hold your breath because for one thing the PDVS2mini is out of stock. But this looks like a good direction for me so I ordered an RPi 400 today to start getting familiar with it. My main meter is a Keysight 34465A so I can get started with logging from that.

**Comment by PhilippCo** [comment]
Hi Chris,
let us include the PDVS. Maybe we can discuss details by mail: philipp.cochems at gmail.com

Best
Philipp

**Comment by PhilippCo** [comment]
I close the issue, because this story became very quiet..
