### ISSUE TITLE
Request: to be able to specify Visa backend

### ISSUE THREAD

**Issue by ggsubs** [PhilippCo/testgear#2]
An optional visa_library initializer would be helpful to chose between the @py or @ivi implementations, just like PyMeasure allows it: 

https://github.com/pymeasure/pymeasure/blob/master/pymeasure/adapters/visa.py

In my experience the Visa implementation is a better choice on Macs.

**Comment by PhilippCo** [comment]
But do we really want to support Apple Products? ;) :P 

Could you start a pull request for that topic? I'm currently very busy, but that gets hopefully better during christams.
